version: 2
jobs:
  deploy_docs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build docs
          command: npm run build
      - run:
          name: Upload docs to GitHub Pages
          command: npx gh-pages -r https://$(echo $GH_TOKEN)@github.com/puregarlic/reviewing-prs.git -d dist -x

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_docs:
          filters:
            branches:
              only: master
